<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="26" hostname="DESKTOP-PO3T4V3" failures="17" tests="54" name="API Integration Automation Test" time="73.362" errors="0" timestamp="2022-10-26T12:54:15 AMT">
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" name="OpenGameAPIValidateStatusCod" time="0.05"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" name="OpenGameAPIValidatePositiveResponse" time="0.009">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
	ResponseObject: null did not expect [null] but found [null],
	ResponseObject Don&amp;apos;t Contain http:// expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
ResponseObject: null did not expect [null] but found [null],
ResponseObject Don't Contain http:// expected [true] but found [false]
at testCases.IqSoft_API_1_OpenGame_Positive_Test.OpenGameAPIValidatePositiveResponse(IqSoft_API_1_OpenGame_Positive_Test.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- OpenGameAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="OpenGameAPIValidateResponseWithInvalidToken" time="0.566"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="OpenGameAPIValidateResponseWithExpiredToken" time="0.614">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.OpenGameAPIValidateResponseWithExpiredToken(IqSoft_API_1_OpenGame_Negative_Test.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- OpenGameAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="OpenGameAPIValidateResponseWithInvalidPartnerID" time="0.643">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode 21 expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.OpenGameAPIValidateResponseWithInvalidPartnerID(IqSoft_API_1_OpenGame_Negative_Test.java:98)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- OpenGameAPIValidateResponseWithInvalidPartnerID -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="OpenGameAPIValidateResponseWithInvalidGameID" time="0.476"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="OpenGameAPIValidateResponseWithInvalidDomain" time="0.632">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [43] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [43] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.OpenGameAPIValidateResponseWithInvalidDomain(IqSoft_API_1_OpenGame_Negative_Test.java:151)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- OpenGameAPIValidateResponseWithInvalidDomain -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidatePositiveResponse" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidateStatusCod" time="0.005"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidatePositiveResponse" time="0.004"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.004"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithExpiredToken" time="0.605">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithExpiredToken(IqSoft_API_2_Authorization_Negative_Test.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidToken" time="0.636"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidProductID" time="0.452">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [43] but found [0],
	Error Description: null expected [ProductNotFound] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description: null expected [ProductNotFound] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidProductID(IqSoft_API_2_Authorization_Negative_Test.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithExpiredToken" time="0.624">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithExpiredToken(IqSoft_API_3_GetBalance_Negative_Test.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidToken" time="0.443"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidCurrencyID" time="0.627">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [20] but found [0],
	Error Description: null expected [CurrencyNotExists] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [20] but found [0],
Error Description: null expected [CurrencyNotExists] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:89)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithInvalidCurrencyID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithOtherCurrencyID" time="0.916">
    <failure type="java.lang.AssertionError" message="balanceUSD VS balanceEUR did not expect [9489.7] but found [9489.7]">
      <![CDATA[java.lang.AssertionError: balanceUSD VS balanceEUR did not expect [9489.7] but found [9489.7]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithOtherCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:113)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithOtherCurrencyID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithExpiredToken" time="1.336">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null],
	amountBeforeCredit = amountAfterCredit: 9489.7 = 9488.7 expected [9488.7] but found [9489.7]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null],
amountBeforeCredit = amountAfterCredit: 9489.7 = 9488.7 expected [9488.7] but found [9489.7]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithExpiredToken(IqSoft_API_4_Credit_Negative_Test.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidToken" time="1.751"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidProductID" time="1.523">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidProductID(IqSoft_API_4_Credit_Negative_Test.java:143)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingTransactionIDTwice" time="2.438"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingAmountHigherThenBalance" time="1.317"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="1.576">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="1.366"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="1.346"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="1.397"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="1.359"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseWithInvalidToken" time="2.215"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidProductID" time="2.528">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidProductID(IqSoft_API_5_Debit_Negative_Test.java:120)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingTransactionIDTwice" time="4.176"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidCreditTransactionID" time="1.309">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [50] but found [0],
	Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
	amountAfterDebit: 9493.7 = amountBeforeDebit: 9488.7 expected [9488.7] but found [9493.7]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [50] but found [0],
Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
amountAfterDebit: 9493.7 = amountBeforeDebit: 9488.7 expected [9488.7] but found [9493.7]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidCreditTransactionID(IqSoft_API_5_Debit_Negative_Test.java:230)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidCreditTransactionID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="2.231"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="2.185"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="2.257"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="2.243"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseWithInvalidToken" time="2.413">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack: 9489.7 = amountAfterCredit: 9488.7 expected [9488.7] but found [9489.7]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack: 9489.7 = amountAfterCredit: 9488.7 expected [9488.7] but found [9489.7]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseWithInvalidToken(IqSoft_API_6_RollBack_Negative_Test.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingInvalidProductID" time="2.198">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack : 9489.7 = amountAfterCredit: 9488.7 expected [9488.7] but found [9489.7]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack : 9489.7 = amountAfterCredit: 9488.7 expected [9488.7] but found [9489.7]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingInvalidProductID(IqSoft_API_6_RollBack_Negative_Test.java:118)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit" time="1.318"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice" time="3.479">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack2 : 9490.7 = amountAfterRollBack1: 9489.7 expected [9489.7] but found [9490.7]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack2 : 9490.7 = amountAfterRollBack1: 9489.7 expected [9489.7] but found [9490.7]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice(IqSoft_API_6_RollBack_Negative_Test.java:218)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice" time="4.097"/>
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
</testsuite> <!-- API Integration Automation Test -->
