<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="26" hostname="DESKTOP-PO3T4V3" failures="19" tests="55" name="API Integration Automation Test" time="30.934" errors="0" timestamp="2022-10-10T12:31:53 AMT">
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" name="openGameAPIValidateStatusCod" time="0.045"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" name="openGameAPIValidatePositiveResponse" time="0.014">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
	ResponseObject: null did not expect [null] but found [null],
	ResponseObject Don&amp;apos;t Contain http:// expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
ResponseObject: null did not expect [null] but found [null],
ResponseObject Don't Contain http:// expected [true] but found [false]
at testCases.IqSoft_API_1_OpenGame_Positive_Test.openGameAPIValidatePositiveResponse(IqSoft_API_1_OpenGame_Positive_Test.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- openGameAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="openGameAPIValidateResponseWithInvalidToken" time="0.274"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="openGameAPIValidateResponseWithExpiredToken" time="0.282">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.openGameAPIValidateResponseWithExpiredToken(IqSoft_API_1_OpenGame_Negative_Test.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- openGameAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="openGameAPIValidateResponseWithInvalidPartnerID" time="0.345">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode 21 expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode 21 expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.openGameAPIValidateResponseWithInvalidPartnerID(IqSoft_API_1_OpenGame_Negative_Test.java:114)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- openGameAPIValidateResponseWithInvalidPartnerID -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="openGameAPIValidateResponseWithInvalidGameID" time="0.168"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="openGameAPIValidateResponseWithInvalidDomain" time="0.367">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [43] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [43] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.openGameAPIValidateResponseWithInvalidDomain(IqSoft_API_1_OpenGame_Negative_Test.java:179)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- openGameAPIValidateResponseWithInvalidDomain -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidateStatusCod" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidateStatusCod" time="0.006"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidatePositiveResponse" time="0.005"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidatePositiveResponse" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidatePositiveResponse" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.009"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithExpiredToken" time="0.19">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithExpiredToken(IqSoft_API_2_Authorization_Negative_Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidToken" time="0.174"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidProductID" time="0.181">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [43] but found [0],
	Error Description: null expected [ProductNotFound] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description: null expected [ProductNotFound] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidProductID(IqSoft_API_2_Authorization_Negative_Test.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithExpiredToken" time="0.178">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithExpiredToken(IqSoft_API_3_GetBalance_Negative_Test.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidToken" time="0.183"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidCurrencyID" time="0.198">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [20] but found [0],
	Error Description: null expected [CurrencyNotExists] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [20] but found [0],
Error Description: null expected [CurrencyNotExists] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:98)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithInvalidCurrencyID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithOtherCurrencyID" time="0.377">
    <failure type="java.lang.AssertionError" message="balanceUSD VS balanceEUR did not expect [9794.0] but found [9794.0]">
      <![CDATA[java.lang.AssertionError: balanceUSD VS balanceEUR did not expect [9794.0] but found [9794.0]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithOtherCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithOtherCurrencyID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithExpiredToken" time="0.539">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null],
	amountBeforeCredit = amountAfterCredit: 9794.0 = 9793.0 expected [9793.0] but found [9794.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null],
amountBeforeCredit = amountAfterCredit: 9794.0 = 9793.0 expected [9793.0] but found [9794.0]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithExpiredToken(IqSoft_API_4_Credit_Negative_Test.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidToken" time="0.556"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidProductID" time="0.548">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidProductID(IqSoft_API_4_Credit_Negative_Test.java:153)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingTransactionIDTwice" time="0.917"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingAmountHigherThenBalance" time="0.548"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.549">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:302)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.544"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.561"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.552"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.567"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseWithInvalidToken" time="0.916"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidProductID" time="0.925">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidProductID(IqSoft_API_5_Debit_Negative_Test.java:126)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingTransactionIDTwice" time="1.656">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [69] but found [0],
	Error Description: null expected [ClientDocumentAlreadyExists] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [69] but found [0],
Error Description: null expected [ClientDocumentAlreadyExists] but found [null]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingTransactionIDTwice(IqSoft_API_5_Debit_Negative_Test.java:201)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingTransactionIDTwice -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidCreditTransactionID" time="0.555">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [50] but found [0],
	Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
	amountBeforeDebit: 9790.0 = amountAfterDebit: 9792.0 expected [9792.0] but found [9790.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [50] but found [0],
Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
amountBeforeDebit: 9790.0 = amountAfterDebit: 9792.0 expected [9792.0] but found [9790.0]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidCreditTransactionID(IqSoft_API_5_Debit_Negative_Test.java:242)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidCreditTransactionID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.942">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:294)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.904"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.922"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.914"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.958"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseWithInvalidToken" time="0.939">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterCredit: 9786.0 = amountAfterRollBack : 9787.0 expected [9787.0] but found [9786.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterCredit: 9786.0 = amountAfterRollBack : 9787.0 expected [9787.0] but found [9786.0]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseWithInvalidToken(IqSoft_API_6_RollBack_Negative_Test.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingInvalidProductID" time="0.92">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack : 9787.0 = amountAfterCredit: 9786.0 expected [9786.0] but found [9787.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack : 9787.0 = amountAfterCredit: 9786.0 expected [9786.0] but found [9787.0]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingInvalidProductID(IqSoft_API_6_RollBack_Negative_Test.java:125)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit" time="0.565"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice" time="1.283">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack1: 9787.0 = amountAfterRollBack2 : 9788.0 expected [9788.0] but found [9787.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack1: 9787.0 = amountAfterRollBack2 : 9788.0 expected [9788.0] but found [9787.0]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice(IqSoft_API_6_RollBack_Negative_Test.java:232)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice" time="1.703"/>
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
</testsuite> <!-- API Integration Automation Test -->
