<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="26" hostname="DESKTOP-PO3T4V3" failures="18" tests="55" name="API Integration Automation Test" time="30.403" errors="0" timestamp="2022-10-07T15:55:59 AMT">
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" name="openGameAPIValidateStatusCod" time="0.039"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" name="openGameAPIValidatePositiveResponse" time="0.015">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [0] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
	did not expect [null] but found [null],
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [0] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
did not expect [null] but found [null],
expected [true] but found [false]
at testCases.IqSoft_API_1_OpenGame_Positive_Test.openGameAPIValidatePositiveResponse(IqSoft_API_1_OpenGame_Positive_Test.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- openGameAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="getUrlAPIValidateResponseWithInvalidToken" time="0.278"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="getUrlAPIValidateResponseWithExpiredToken" time="0.279">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.getUrlAPIValidateResponseWithExpiredToken(IqSoft_API_1_OpenGame_Negative_Test.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getUrlAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="getUrlAPIValidateResponseWithInvalidPartnerID" time="0.308">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [22] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.getUrlAPIValidateResponseWithInvalidPartnerID(IqSoft_API_1_OpenGame_Negative_Test.java:108)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getUrlAPIValidateResponseWithInvalidPartnerID -->
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="getUrlAPIValidateResponseWithInvalidGameID" time="0.248"/>
  <testcase classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" name="getUrlAPIValidateResponseWithInvalidDomain" time="0.351">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [43] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [43] but found [21],
Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]
at testCases.IqSoft_API_1_OpenGame_Negative_Test.getUrlAPIValidateResponseWithInvalidDomain(IqSoft_API_1_OpenGame_Negative_Test.java:169)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getUrlAPIValidateResponseWithInvalidDomain -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.005"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithExpiredToken" time="0.183">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithExpiredToken(IqSoft_API_2_Authorization_Negative_Test.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidToken" time="0.18"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidProductID" time="0.194">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [43] but found [0],
	Error Description: null expected [ProductNotFound] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [43] but found [0],
Error Description: null expected [ProductNotFound] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidProductID(IqSoft_API_2_Authorization_Negative_Test.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithExpiredToken" time="0.188">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithExpiredToken(IqSoft_API_3_GetBalance_Negative_Test.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidToken" time="0.199"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidCurrencyID" time="0.183">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [20] but found [0],
	Error Description: null expected [CurrencyNotExists] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [20] but found [0],
Error Description: null expected [CurrencyNotExists] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithInvalidCurrencyID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithOtherCurrencyID" time="0.362">
    <failure type="java.lang.AssertionError" message="did not expect [9835.0] but found [9835.0]">
      <![CDATA[java.lang.AssertionError: did not expect [9835.0] but found [9835.0]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithOtherCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:118)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithOtherCurrencyID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithExpiredToken" time="0.558">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null],
	expected [9834.0] but found [9835.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null],
expected [9834.0] but found [9835.0]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithExpiredToken(IqSoft_API_4_Credit_Negative_Test.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidToken" time="0.536"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidProductID" time="0.58">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidProductID(IqSoft_API_4_Credit_Negative_Test.java:145)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingTransactionIDTwice" time="0.952"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingAmountHigherThenBalance" time="0.542"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.566">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:287)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.565"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.557"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.541"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.55"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseWithInvalidToken" time="0.889"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidProductID" time="0.921">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error Description: game not avaible expected [game not available] but found [game not avaible]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidProductID(IqSoft_API_5_Debit_Negative_Test.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingTransactionIDTwice" time="1.625">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [69] but found [43],
	Error Description: game not avaible expected [ClientDocumentAlreadyExists] but found [game not avaible],
	expected [9827.0] but found [9829.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [69] but found [43],
Error Description: game not avaible expected [ClientDocumentAlreadyExists] but found [game not avaible],
expected [9827.0] but found [9829.0]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingTransactionIDTwice(IqSoft_API_5_Debit_Negative_Test.java:195)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingTransactionIDTwice -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidCreditTransactionID" time="0.56">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [50] but found [0],
	Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
	expected [9831.0] but found [9829.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [50] but found [0],
Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
expected [9831.0] but found [9829.0]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidCreditTransactionID(IqSoft_API_5_Debit_Negative_Test.java:234)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidCreditTransactionID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.916">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [39] but found [0],
Error Description: null expected [WrongOperationAmount] but found [null]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:284)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.933"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.908"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.895"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="0.918"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseWithInvalidToken" time="0.879">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountBeforeRollBack amountAfterRollBack expected [9826.0] but found [9825.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountBeforeRollBack amountAfterRollBack expected [9826.0] but found [9825.0]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseWithInvalidToken(IqSoft_API_6_RollBack_Negative_Test.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingInvalidProductID" time="0.918">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountBeforeRollBack amountAfterRollBack expected [9826.0] but found [9825.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountBeforeRollBack amountAfterRollBack expected [9826.0] but found [9825.0]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingInvalidProductID(IqSoft_API_6_RollBack_Negative_Test.java:129)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingInvalidTransactionID" time="0.555"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice" time="1.266"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameTransactionIDTwice" time="1.583"/>
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
</testsuite> <!-- API Integration Automation Test -->
